# Generated by Django 4.2.7 on 2026-01-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='SUCCESS', max_length=16)),
                ('model_name', models.CharField(max_length=255)),
                ('prompt_version', models.CharField(default='v1', max_length=64)),
                ('llm_label', models.CharField(choices=[('LEGIT', 'LEGIT'), ('SUSPICIOUS', 'SUSPICIOUS'), ('FRAUD', 'FRAUD'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=16)),
                ('llm_confidence', models.FloatField(default=0.0)),
                ('llm_rationale', models.TextField(blank=True, null=True)),
                ('llm_json', models.TextField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='apps_store.mobileapp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'created_at'], name='analysis_an_app_id_89eb79_idx'), models.Index(fields=['created_by', 'created_at'], name='analysis_an_created_64b2d9_idx'), models.Index(fields=['llm_label'], name='analysis_an_llm_lab_c06f8f_idx')],
            },
        ),
    ]
