# Generated by Django 5.2.10 on 2026-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='safety_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
    ]
