# Generated by Django 5.2.10 on 2026-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='privacy_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
