# Generated by Django 4.2.7 on 2026-01-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apps_store.mobileapp')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'created_at'], name='reviews_rev_app_id_e592a4_idx'), models.Index(fields=['app', 'review_date'], name='reviews_rev_app_id_f921b9_idx')],
            },
        ),
    ]
